# Generated by Django 5.2.17 on 2026-09-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('course_interest', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('activecampaign_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('CONTACTED', 'Contacted'), ('REPLIED', 'Replied'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not interested'), ('REQUIRES_HUMAN', 'Requires human'), ('DO_NOT_CONTACT', 'Do not contact'), ('INVALID', 'Invalid')], db_index=True, default='NEW', max_length=32)),
                ('do_not_contact', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name', 'id'),
            },
        ),
    ]
