# Generated by Django 5.2.17 on 2026-09-14 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outbound_enabled', models.BooleanField(default=True)),
                ('inbound_auto_reply_enabled', models.BooleanField(default=False)),
                ('paused_reason', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_state_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system state',
                'verbose_name_plural': 'system state',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], max_length=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('READY', 'Ready'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REQUIRES_HUMAN', 'Requires human')], db_index=True, default='PENDING', max_length=24)),
                ('content', models.TextField(blank=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='campaigns.campaign')),
                ('campaign_member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='campaigns.campaignmember')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='candidates.candidate')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['direction', 'status', 'scheduled_at'], name='message_queue_lookup')],
            },
        ),
    ]
