# Generated by Django 5.2.17 on 2026-09-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
        ('candidates', '0002_candidate_unique_nonblank_candidate_phone_and_more'),
        ('messaging', '0002_create_system_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='unique_nonblank_message_idempotency_key'),
        ),
    ]
