# Generated by Django 5.2.17 on 2026-09-15 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_alter_auditevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('CSV_IMPORTED', 'CSV imported'), ('CANDIDATE_CREATED', 'Candidate created'), ('CANDIDATE_UPDATED', 'Candidate updated'), ('DUPLICATE_DETECTED', 'Duplicate detected'), ('CAMPAIGN_MEMBER_CREATED', 'Campaign member created'), ('MESSAGE_QUEUED', 'Message queued'), ('MESSAGE_GENERATED', 'Message generated'), ('MESSAGE_APPROVED', 'Message approved'), ('MESSAGE_BLOCKED', 'Message blocked'), ('MESSAGE_SENT', 'Message sent'), ('MESSAGE_FAILED', 'Message failed'), ('OPT_OUT_DETECTED', 'Opt-out detected'), ('SYSTEM_PAUSED', 'System paused'), ('SYSTEM_RESUMED', 'System resumed'), ('HUMAN_ESCALATION', 'Human escalation'), ('AGENT_ERROR', 'Agent error')], db_index=True, max_length=40),
        ),
    ]
