# Generated by Django 5.2.17 on 2026-09-14 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=16)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('min_message_interval_seconds', models.PositiveIntegerField(default=120)),
                ('hourly_limit', models.PositiveIntegerField(default=20)),
                ('daily_limit', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(('hourly_limit__gt', 0)), name='campaign_hourly_limit_gt_zero'), models.CheckConstraint(condition=models.Q(('daily_limit__gt', 0)), name='campaign_daily_limit_gt_zero'), models.CheckConstraint(condition=models.Q(('start_at__isnull', True), ('end_at__isnull', True), ('start_at__lte', models.F('end_at')), _connector='OR'), name='campaign_dates_in_order')],
            },
        ),
        migrations.CreateModel(
            name='CampaignMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('CONTACTED', 'Contacted'), ('REPLIED', 'Replied'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not interested'), ('COMPLETED', 'Completed'), ('SKIPPED', 'Skipped')], db_index=True, default='READY', max_length=24)),
                ('first_contact_at', models.DateTimeField(blank=True, null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('replies_received', models.PositiveIntegerField(default=0)),
                ('human_required', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='campaigns.campaign')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_memberships', to='candidates.candidate')),
            ],
            options={
                'ordering': ('campaign', 'candidate'),
                'constraints': [models.UniqueConstraint(fields=('campaign', 'candidate'), name='unique_candidate_per_campaign'), models.CheckConstraint(condition=models.Q(('first_contact_at__isnull', True), ('last_contact_at__isnull', True), ('first_contact_at__lte', models.F('last_contact_at')), _connector='OR'), name='campaign_member_contact_dates_in_order')],
            },
        ),
    ]
